// This is the single source for the public DEVLOG and ROADMAP sections.
export const devlog=[{date:'2026-09-15',title:'002 / From looking to learning',paragraphs:[
  'Built: Kaktovik, Maya, and 正 tally bring the gallery to nine systems. The quick study adds typed reading and exact part-composition exercises, with attempts, accuracy, median response time, and confusion pairs stored only on the viewer’s device.',
  'Browser finding: switching from composition back to reading initially left interactive ghost parts inside the reading glyph. The stage now resets at a mode or system boundary while preserving keyed transitions between questions in the same mode.',
  'Kaktovik finding: the first straight-stroke geometry made 19 cross itself. A first correction separated the components too far and reversed 10 into a left-pointing form. Direct visual review established the construction rule: 10 points right, and the unit zigzag grows from the five-group’s lower-left attachment point. In 16, the bottom-left joint of 15 and the top of 1 are now exactly the same coordinate.',
  'Motion finding: part exits now linger as an afterglow or retract, while added parts draw in. Adjacent steps stagger place changes by 40 ms from least significant to most significant. These timings are design defaults, not measured perceptual optima.',
  'Verified in Safari: nine cards render, read answers score and persist, Kaktovik 12 can be composed from two five-strokes plus two one-strokes, quiz modes clear their previous interaction layer, and both desktop and narrow responsive layouts remain usable. Testing on a physical phone and sustained frame-rate measurement remain open.'
]},{date:'2026-09-15',title:'001 / The first playground',paragraphs:[
  'Built: six representations of a shared number, three surfaces, count up/down, single-step controls, and an expanded reading guide. Everything runs as native JavaScript and SVG, with no build step or runtime package dependencies.',
  'Observed in the encoding: 15 → 16 removes four active binary bits and adds one. Ink quantity is not a reliable proxy for magnitude in a positional system. Whether this feels confusing is a question for people, not something the code alone can answer.',
  'Design finding: an empty inner Ko ring needs an explicit position marker. This prototype uses a short tick for a zero digit; the value zero itself remains a centre dot. We should compare this convention with faint complete guide rings.',
  'Reference review: dexipurei-galore supplies the shared-input/card/full-view interaction precedent and orange glow vocabulary. CistercianWeave confirms the quadrant geometry. No sibling source was vendored. Kaktovik remains in iterative geometry review.',
  'Not yet measured: reading speed, accuracy, perceived similarity, phone frame rate, and the effect of skin on legibility. Animation currently fades in added parts and removes departing parts immediately; afterglow, moving parts, and carry cascades remain future work.'
]}];
export const roadmap=[
  {status:'BUILT · PLAY & STUDY',title:'Make the differences tangible',items:['Nine systems, including Kaktovik, Maya, and 正 tally','Read and compose study modes with device-local statistics','Ghost lattices, exit afterglow, draw-on, and carry staggering','Desktop and narrow Safari interaction checks','DEVLOG and ROADMAP as living project content']},
  {status:'NEXT · TEST & DEEPEN',title:'Turn sessions into evidence',items:['Human visual review of Kaktovik and Maya geometry','Phone layout, reduced-motion, and sustained performance checks','Choice quiz with structurally similar distractors','Confusion-pair table and value error heatmap','Export and import local study statistics']},
  {status:'LATER · EXPAND THE LAB',title:'Measure, then invent',items:['Timer and ammo experiments; test positional carry against erosion','Extended historical catalog and source notes','Geometry-aware similarity and measured reading experiments','Embeddable display component and offline support','Forge: design, save, compare, and export original systems']}
];
