// This is the single source for the public DEVLOG and ROADMAP sections.
export const devlog=[{date:'2026-09-15',title:'003 / Near neighbours',paragraphs:[
  'Built: Choice mode presents four decimal answers for the displayed glyph. Its distractors are selected by structural distance—the number of glyph parts that would need to be added or removed—then by numerical proximity. This makes the choices plausible within each notation instead of merely random.',
  'Measurement finding: choosing a wrong answer records the exact target → choice pair in the same device-local statistics model used by Read and Compose. This gives the future confusion table meaningful observations without sending study data anywhere.',
  'Design caveat: equal part count does not guarantee equal perceptual similarity. The current heuristic is intentionally legible and testable; observed confusion pairs should eventually replace its assumptions.',
  'Implementation checks: choice sets contain one target and three unique nearby structures. Selection locks all choices, identifies both the chosen and correct values, overlays the structural difference after a wrong answer, and maintains separate per-system Choice statistics. Extended browser and phone sessions remain part of the next testing pass.'
]},{date:'2026-09-15',title:'002 / From looking to learning',paragraphs:[
  'Built: Kaktovik, Maya, and 正 tally bring the gallery to nine systems. The quick study adds typed reading and exact part-composition exercises, with attempts, accuracy, median response time, and confusion pairs stored only on the viewer’s device.',
  'Browser finding: switching from composition back to reading initially left interactive ghost parts inside the reading glyph. The stage now resets at a mode or system boundary while preserving keyed transitions between questions in the same mode.',
  'Kaktovik finding: treating 5, 10, and 15 as isolated silhouettes broke the cumulative logic—the same five-stroke moved as the value grew, and compound digits could cross themselves. The corrected ladder keeps 5 as the bottom five-stroke, adds one stroke above it to make 10, and adds another above that to make 15. Unit strokes occupy a fixed lower region and join the same lower-left anchor, so every part now keeps both its identity and geometry across 1–19.',
  'Motion finding: part exits now linger as an afterglow or retract, while added parts draw in. Adjacent steps stagger place changes by 40 ms from least significant to most significant. These timings are design defaults, not measured perceptual optima.',
  'Verified in Safari: nine cards render, read answers score and persist, Kaktovik 12 can be composed from two five-strokes plus two one-strokes, quiz modes clear their previous interaction layer, and both desktop and narrow responsive layouts remain usable. Testing on a physical phone and sustained frame-rate measurement remain open.'
]},{date:'2026-09-15',title:'001 / The first playground',paragraphs:[
  'Built: six representations of a shared number, three surfaces, count up/down, single-step controls, and an expanded reading guide. Everything runs as native JavaScript and SVG, with no build step or runtime package dependencies.',
  'Observed in the encoding: 15 → 16 removes four active binary bits and adds one. Ink quantity is not a reliable proxy for magnitude in a positional system. Whether this feels confusing is a question for people, not something the code alone can answer.',
  'Design finding: an empty inner Ko ring needs an explicit position marker. This prototype uses a short tick for a zero digit; the value zero itself remains a centre dot. We should compare this convention with faint complete guide rings.',
  'Reference review: dexipurei-galore supplies the shared-input/card/full-view interaction precedent and orange glow vocabulary. CistercianWeave confirms the quadrant geometry. No sibling source was vendored. Kaktovik remains in iterative geometry review.',
  'Not yet measured: reading speed, accuracy, perceived similarity, phone frame rate, and the effect of skin on legibility. Animation currently fades in added parts and removes departing parts immediately; afterglow, moving parts, and carry cascades remain future work.'
]}];
export const roadmap=[
  {status:'BUILT · PLAY & STUDY',title:'Make the differences tangible',items:['Nine systems, including Kaktovik, Maya, and 正 tally','Read, structure-matched Choice, and Compose study modes','Device-local timing, accuracy, and confusion-pair statistics','Ghost lattices, exit afterglow, draw-on, and carry staggering','DEVLOG and ROADMAP as living project content']},
  {status:'NEXT · TEST & DEEPEN',title:'Turn sessions into evidence',items:['Human visual review of Maya geometry and continued Kaktovik review','Phone layout, reduced-motion, and sustained performance checks','Confusion-pair table and value error heatmap','Export and import local study statistics','Use observed confusions to improve Choice distractors']},
  {status:'LATER · EXPAND THE LAB',title:'Measure, then invent',items:['Timer and ammo experiments; test positional carry against erosion','Extended historical catalog and source notes','Geometry-aware similarity and measured reading experiments','Embeddable display component and offline support','Forge: design, save, compare, and export original systems']}
];
