import {render} from './core/render-svg.js';
import {templateFor,isStructuralPart} from './core/template.js';
const NS='http://www.w3.org/2000/svg';
const $=id=>document.getElementById(id);
const storageKey='suji-quiz-stats-v1';
function readStats(){try{return JSON.parse(localStorage.getItem(storageKey))||{};}catch{return {};}}
function saveStats(stats){try{localStorage.setItem(storageKey,JSON.stringify(stats));}catch{}}
function sameSet(a,b){return a.size===b.size&&[...a].every(id=>b.has(id));}
function median(values){if(!values.length)return null;const sorted=[...values].sort((a,b)=>a-b),i=Math.floor(sorted.length/2);return sorted.length%2?sorted[i]:Math.round((sorted[i-1]+sorted[i])/2);}

export function initQuiz(systems,getSkin){
  const select=$('quiz-system'),read=$('quiz-read'),compose=$('quiz-compose'),form=$('quiz-form'),answer=$('quiz-answer'),stage=$('quiz-stage');
  for(const system of systems){const option=document.createElement('option');option.value=system.id;option.textContent=`${system.name} · ${system.ja}`;select.append(option);}
  select.value='kaktovik';let system=systems.find(s=>s.id===select.value),mode='read',target=0,started=0,locked=false,chosen=new Set(),stats=readStats();
  function statKey(){return `${system.id}:${mode}`;}
  function currentStats(){return stats[statKey()]||{attempts:0,correct:0,times:[],confusions:{}};}
  function updateStats(){const s=currentStats(),m=median(s.times);$('quiz-score').textContent=`${s.correct} / ${s.attempts}`;$('quiz-accuracy').textContent=s.attempts?`${Math.round(s.correct/s.attempts*100)}% accurate`:'No attempts yet';$('quiz-time').textContent=m===null?'Median time —':`Median time ${(m/1000).toFixed(1)} s`;}
  function drawCompose(){stage.dataset.skin=getSkin();stage.className='stage';stage.replaceChildren();const template=templateFor(system);const svg=document.createElementNS(NS,'svg');svg.setAttribute('viewBox',`-6 -6 ${template.box.w+12} ${template.box.h+12}`);svg.setAttribute('role','group');svg.setAttribute('aria-label',`Compose ${target} in ${system.name}`);
    for(const part of template.parts){const fixed=isStructuralPart(part.id),el=document.createElementNS(NS,'path');if(fixed)chosen.add(part.id);const selected=chosen.has(part.id);el.setAttribute('d',part.d);el.dataset.part=part.id;el.setAttribute('vector-effect','non-scaling-stroke');el.setAttribute('class',`part compose-part group-${part.group}${part.fill?' filled':''}${fixed?' fixed':''}${selected?' selected':''}`);if(!fixed){el.setAttribute('role','button');el.setAttribute('tabindex','0');el.setAttribute('aria-label',`Toggle part ${part.id}`);el.setAttribute('aria-pressed',String(selected));const toggle=()=>{if(locked)return;chosen.has(part.id)?chosen.delete(part.id):chosen.add(part.id);el.classList.toggle('selected',chosen.has(part.id));el.setAttribute('aria-pressed',String(chosen.has(part.id)));};el.addEventListener('click',toggle);el.addEventListener('keydown',event=>{if(event.key==='Enter'||event.key===' '){event.preventDefault();toggle();}});}svg.append(el);}stage.append(svg);
  }
  function next(){locked=false;chosen=new Set();answer.disabled=false;answer.value='';$('quiz-feedback').textContent='';$('quiz-feedback').className='quiz-feedback';$('quiz-next').hidden=true;$('quiz-check').hidden=false;const limit=mode==='compose'?system.composeMax:system.quizMax;let next=target;while(next===target&&limit>0)next=Math.floor(Math.random()*(limit+1));target=next;started=performance.now();
    if(mode==='read'){$('quiz-prompt').textContent='What value is this?';$('quiz-instruction').textContent='Read the glyph, enter its decimal value, and check your answer.';answer.hidden=false;form.querySelector('label').hidden=false;render(stage,system,target,{skin:getSkin()});queueMicrotask(()=>answer.focus());}
    else{$('quiz-prompt').textContent=`Build ${target.toLocaleString()}`;$('quiz-instruction').textContent='Tap the faint parts to construct the shown decimal value, then check the exact shape.';answer.hidden=true;form.querySelector('label').hidden=true;drawCompose();}
  }
  function markReadDifference(guess){if(!system.canRender(guess))return;const wanted=system.layout(target),wrong=system.layout(guess),wantIds=new Set(wanted.parts.map(p=>p.id)),wrongIds=new Set(wrong.parts.map(p=>p.id)),svg=stage.querySelector('svg');for(const el of svg?.querySelectorAll('[data-layer="active"]')||[])if(!wrongIds.has(el.dataset.part))el.classList.add('wrong-part');for(const part of wrong.parts)if(!wantIds.has(part.id)){const el=document.createElementNS(NS,'path');el.setAttribute('d',part.d);el.setAttribute('class',`part wrong-part${part.fill?' filled':''}`);el.setAttribute('vector-effect','non-scaling-stroke');svg?.append(el);}}
  function check(event){event?.preventDefault();if(locked)return;let correct=false,guess=null;if(mode==='read'){guess=Number(answer.value);if(!Number.isInteger(guess)){$('quiz-feedback').textContent='Enter a whole number first.';$('quiz-feedback').className='quiz-feedback wrong';return;}correct=guess===target;if(!correct)markReadDifference(guess);}else{const expected=new Set(system.layout(target).parts.map(p=>p.id));correct=sameSet(chosen,expected);try{guess=system.decode([...chosen]);if(!Number.isFinite(guess))guess='non-canonical';}catch{guess='non-canonical';}for(const el of stage.querySelectorAll('.compose-part')){const should=expected.has(el.dataset.part),has=chosen.has(el.dataset.part);if(should!==has)el.classList.add('wrong-part');}}
    locked=true;answer.disabled=true;const s=currentStats();s.attempts++;if(correct)s.correct++;const elapsed=Math.round(performance.now()-started);s.times.push(elapsed);if(s.times.length>100)s.times.shift();if(!correct){const key=`${target}→${guess}`;s.confusions[key]=(s.confusions[key]||0)+1;}stats[statKey()]=s;saveStats(stats);updateStats();$('quiz-feedback').textContent=correct?`Correct · ${(elapsed/1000).toFixed(1)} s`:`Not quite · ${target} was the target${mode==='read'?` (you entered ${guess})`:''}`;$('quiz-feedback').className=`quiz-feedback ${correct?'correct':'wrong'}`;$('quiz-check').hidden=true;$('quiz-next').hidden=false;$('quiz-next').focus();
  }
  function resetStage(){stage.replaceChildren();stage.removeAttribute('data-value');}
  function setMode(nextMode){if(nextMode==='compose'&&!system.composeSeeds)return;mode=nextMode;resetStage();read.setAttribute('aria-pressed',String(mode==='read'));compose.setAttribute('aria-pressed',String(mode==='compose'));updateStats();next();}
  select.onchange=()=>{system=systems.find(s=>s.id===select.value);compose.disabled=!system.composeSeeds;if(mode==='compose'&&!system.composeSeeds)mode='read';resetStage();read.setAttribute('aria-pressed',String(mode==='read'));compose.setAttribute('aria-pressed',String(mode==='compose'));updateStats();next();};
  read.onclick=()=>setMode('read');compose.onclick=()=>setMode('compose');form.onsubmit=check;$('quiz-next').onclick=next;$('quiz-reset').onclick=()=>{delete stats[statKey()];saveStats(stats);updateStats();next();};
  compose.disabled=!system.composeSeeds;updateStats();next();
  return{refresh(){if(mode==='read'&&!locked)render(stage,system,target,{skin:getSkin()});else if(mode==='compose'&&!locked)drawCompose();}};
}
